In [12]:
import uuid
def get_uuid():
    return str(uuid.uuid4())

In [1]:
from models import get_embed

In [2]:
embed = get_embed()

In [3]:
from chromadb import HttpClient

D:\software\anaconda3\Lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(


In [4]:
chroma_client = HttpClient(host='localhost', port=8000)

In [5]:
collection = chroma_client.get_or_create_collection(name="langchain")

In [6]:
# 插入：
documents = ["今天很高兴", "外面下雨了"]

In [10]:
embeddings = [embed.embed_query(sentence) for sentence in documents]

In [13]:
ids = [get_uuid() for _ in range(len(documents))]

In [15]:
collection.add(ids=ids, documents=documents, embeddings=embeddings)

In [18]:
results = collection.get(include=["documents", "embeddings"])

In [19]:
type(results)

dict

In [20]:
results.keys()

dict_keys(['ids', 'embeddings', 'metadatas', 'documents', 'data', 'uris', 'included'])

In [24]:
v1, v2 = results["embeddings"]

In [25]:
v1

array([-0.02312675,  0.03950341, -0.05403913, ..., -0.00152572,
       -0.05192972, -0.03796929])

In [27]:
import numpy as np

In [28]:
v = np.array(embed.embed_query(text="今天很高兴"))

In [29]:
v

array([-0.02312675,  0.03950341, -0.05403913, ..., -0.00152572,
       -0.05192972, -0.03796929])

In [30]:
v1

array([-0.02312675,  0.03950341, -0.05403913, ..., -0.00152572,
       -0.05192972, -0.03796929])

In [31]:
np.allclose(v, v1)

True

In [32]:
# 语义检索
text = "外面天气怎么样？"

In [34]:
embedding = embed.embed_query(text=text)

In [40]:
collection.query(query_embeddings=embedding, n_results=1)

{'ids': [['6c97e056-9644-4b9a-ac58-74c044f8c0c5']],
 'distances': [[0.49125819017337796]],
 'embeddings': None,
 'metadatas': [[None]],
 'documents': [['外面下雨了']],
 'uris': None,
 'data': None,
 'included': ['distances', 'documents', 'metadatas']}