In [53]:
import torch

In [54]:
attn_shape = (1, 5, 5)

In [55]:
torch.triu(torch.ones(attn_shape), diagonal=1).type(torch.uint8) == 0

tensor([[[ True, False, False, False, False],
         [ True,  True, False, False, False],
         [ True,  True,  True, False, False],
         [ True,  True,  True,  True, False],
         [ True,  True,  True,  True,  True]]])

In [58]:
torch.tril(torch.ones(attn_shape)).type(torch.bool) == False

tensor([[[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]]])

In [59]:
A = torch.randn(2, 3, 4)

In [21]:
B = torch.randn(2, 3, 4)

In [19]:
torch.matmul(input=A, other=B)

torch.Size([3, 3])

In [22]:
a = torch.randn(5)
b = torch.randn(5)

In [23]:
a

tensor([-0.7032, -0.6083,  1.7877,  0.2349,  1.4872])

In [24]:
b

tensor([-0.4334, -0.1245, -0.6855, -0.9446, -1.2565])

In [25]:
torch.matmul(a, b)

tensor(-2.9356)

In [26]:
a @ b

tensor(-2.9356)

In [27]:
a = torch.randn(3, 4)

In [28]:
b = torch.randn(4, 3)

In [29]:
torch.matmul(a, b)

tensor([[-0.4010, -0.0625,  0.2116],
        [-1.2672,  1.1866, -0.7347],
        [-0.5078,  1.1611, -0.6804]])

In [30]:
a @ b

tensor([[-0.4010, -0.0625,  0.2116],
        [-1.2672,  1.1866, -0.7347],
        [-0.5078,  1.1611, -0.6804]])

In [48]:
# [batch_size, seq_len, embed_dim]
q = torch.randn(2, 70, 128)

In [49]:
# [batch_size, seq_len, embed_dim]
k = torch.randn(2, 70, 128)

In [51]:
# batched matrix multiply
q_dot_k = torch.bmm(q, k.permute(dims=(0, 2, 1)))

In [52]:
# # [batch_size, seq_len, seq_len]
q_dot_k.shape

torch.Size([2, 70, 70])

In [62]:
scores = torch.randn(3)

In [67]:
scores

tensor([-0.2162, -0.9191,  1.0498])

In [75]:
mask = torch.tensor(data=[1, 0, 1], dtype=torch.bool)
mask

tensor([ True, False,  True])

In [76]:
scores.masked_select(mask=mask)

tensor([-0.2162,  1.0498])

In [77]:
a = 512
b = 8

In [78]:
a %  b

0

In [88]:
# 断言 常用语测试代码
assert True, "有错误"

In [90]:
2 // 1

2

In [91]:
a = [1, 2, 3, 4]

In [92]:
b = "abc"

In [93]:
for x, y in zip(a, b):
    print(x, y)

1 a
2 b
3 c


In [94]:
from ultralytics import YOLO

In [96]:
model = YOLO()

In [97]:
model

YOLO(
  (model): DetectionModel(
    (model): Sequential(
      (0): Conv(
        (conv): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(16, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): C3k2(
        (cv1): Conv(
          (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(48, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_