In [1]:
from sklearn.datasets import load_iris

In [2]:
# 加载数据集
iris = load_iris()

In [3]:
# 加载特征数据
X = iris.data
print(f'特征数据：{X}')

特征数据：[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3

In [4]:
# 加载目标数据
y = iris.target
print(f'特征数据：{y}')

特征数据：[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [5]:
from sklearn.model_selection import train_test_split

In [6]:
# 进行数据切分
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, shuffle=True)

In [7]:
X_train.shape

(120, 4)

In [8]:
X_test.shape

(30, 4)

In [9]:
y_train.shape

(120,)

In [10]:
y_test.shape

(30,)

In [11]:
# 引入一个模型，这里用KNN
from sklearn.neighbors import KNeighborsClassifier

In [12]:
# 构建模型
knn = KNeighborsClassifier()

In [13]:
# 训练模型
knn.fit(X=X_train, y=y_train)

KNeighborsClassifier()

In [14]:
# 预测，奖结果保存至y_pred
y_pred = knn.predict(X=X_test)

In [15]:
# 计算准确率
acc = (y_pred == y_test).mean()

In [16]:
acc

np.float64(0.9666666666666667)

In [17]:
# 这次引入 决策树模型
from sklearn.tree import DecisionTreeClassifier

In [18]:
# 构建模型
dtc = DecisionTreeClassifier()

In [19]:
# 训练
dtc.fit(X=X_train, y=y_train)

DecisionTreeClassifier()

In [20]:
# 预测
y_pred2 = dtc.predict(X=X_test)

In [21]:
# 计算准确率
acc2 = (y_pred2 == y_test).mean()

In [22]:
acc2

np.float64(1.0)

In [23]:
# 这次引入 向量机模型
from sklearn.svm import SVC

In [24]:
# 构建模型
svc = SVC()

In [25]:
# 训练模型
svc.fit(X=X_train, y=y_train)

SVC()

In [26]:
# 预测
y_pred3 = svc.predict(X=X_test)

In [27]:
# 计算准确率
acc3 = (y_pred3 == y_test).mean()

In [28]:
acc3

np.float64(1.0)

### 部署模型

In [29]:
import joblib
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [30]:
# 准备数据
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, random_state=0, test_size=0.2)

In [31]:
# 构建模型
knn = KNeighborsClassifier()
# 训练
knn.fit(X=X_train, y=y_train)
# 预测
y_pred = knn.predict(X=X_test)
# 计算准确率
acc = (y_pred == y_test).mean()

In [32]:
acc

np.float64(0.9666666666666667)

In [33]:
# 序列化 模型
joblib.dump(value=knn, filename="knn.pmz")

['knn.pmz']

### 反序列化

In [34]:
import joblib
import numpy as np

In [35]:
# 加载 硬盘中的模型
knn = joblib.load(filename="knn.pmz")

In [36]:
# 制作假数据
X = np.array([[4.9, 3.1, 3.5, 1.2]])

In [37]:
# 预测
y_pred = knn.predict(X=X)

In [38]:
y_pred

array([1])