# 1.传统计算

In [1]:
scores = [78, 45, 76, 23, 90]

In [2]:
# 计算有多少个同学
len(scores)

5

In [3]:
# 平均分
sum(scores) / len(scores)

62.4

In [4]:
# 最高分
max(scores)

90

In [5]:
# 最低分
min(scores)

23

In [6]:
# 方差， 没有办法直接求

In [7]:
# 每个同学加 5 分， 只能遍历
[i + 5 for i in scores]

[83, 50, 81, 28, 95]

# 2.科学计算
- 向量化计算
- 矩阵计算
- 高性能计算
- 线性代数
- GPU之类的
- NumPy
    - 科学计算神器！
    - 通用科学计算库
    - 深度学习框架 PyTorch，本质上是一个 NumPy++
    - 容器：NDArray  N为数组
    - 算法：各种数据处理方法

In [8]:
import numpy as np

In [39]:
print(np.random.randn(2,3))

[[-0.80749527 -0.16468945 -1.27244665]
 [-0.43535358  1.33707246 -0.37294362]]


In [9]:
scores = [78, 45, 76, 23, 90]

In [10]:
arr = np.array(scores)

In [11]:
arr

array([78, 45, 76, 23, 90])

In [12]:
arr.min()

np.int64(23)

In [13]:
arr.max()

np.int64(90)

In [14]:
arr.size

5

In [15]:
# 平均值
arr.mean()

np.float64(62.4)

In [16]:
# 方差
arr.var()

np.float64(609.0400000000001)

In [17]:
# 标准差
arr.std()

np.float64(24.67873578609731)

In [18]:
# 广播机制，5会自动对齐成一个向量
arr + 5

array([83, 50, 81, 28, 95])

In [19]:
# 连续均匀分布[0，1) 前闭后开，不包含1
np.random.rand()

0.6895759076191925

In [20]:
# 离散均匀分布[low, high) 前闭后开，不包含high
np.random.randint(low=0, high=101, size=30)

array([67, 15, 24, 15, 34, 28, 24, 81, 94,  3,  7, 97, 91, 71, 46, 21, 82,
       61, 93, 70,  5,  6,  4, 55,  5, 19, 33, 55, 16, 84], dtype=int32)

In [21]:
# 标准正态分布/高斯分布/标准高斯分布 mu(均值)=0， sigma(标准差)=1
np.random.randn(10)

array([-0.67285747, -0.71532038,  0.26818598,  0.17010779,  0.33767336,
        0.37471451, -0.83630808,  0.24421576,  0.47498205,  2.31080301])

In [22]:
a = np.random.randint(low=0, high=11, size=5)
b = np.random.randint(low=0, high=11, size=5)

In [23]:
a

array([9, 9, 4, 0, 5], dtype=int32)

In [24]:
b

array([ 6,  8,  3, 10,  8], dtype=int32)

向量的模，向量的模就是向量的长度。

在坐标系中，就是把向量分别投射到x轴和y轴，会得到一个坐标(x,y)， 它的长度就是这个坐标到(0,0)的距离。

根据勾股定理，模就是 $\sqrt{x^2 + y^2}$ ， 如果是高纬度，则是 $\sqrt{x^2 + y^2 + ... + n^2}$

In [25]:
# 取a向量的模
(a ** 2).sum() ** 0.5

np.float64(14.247806848775006)

In [26]:
# 向量的模也可以用这个
np.linalg.norm(a)

np.float64(14.247806848775006)

In [27]:
# 向量求内积/点乘积
# 注意力机制的核心。dot product

两个向量的乘积：$a·b = |a|·|b|·\cos\theta$ ， 内积的结果是个标量

$\cos$是 临边/斜边

In [28]:
(a * b).sum()

np.int64(178)

In [29]:
#内积也可以这么写
a @ b

np.int32(178)

### 余弦相似度
- 本质：使用向量的`夹角`的余弦来代表向量的相似情况
    - 0°：相似度1，相似度是最高的
    - 90°：相似度为0，相似度是中等的
    - 180°：相似度-1，相似度是反向
    - 余弦相似度越大，代表两个向量越相似
    - 的确存在逻辑上的错误！！！
    - 大数据的核心是：工程折中！！！不是精准核算！！！
    - 从纯数学角度看，一切模型都是错的！！
    - 从工程角度看，大部分模型是有效的！！
    - 半科研，半工程

In [30]:
# 求余弦相似度， 余弦相似度越高说明他们越相似
cosine_similarity = a @ b / np.linalg.norm(a) / np.linalg.norm(b)

In [31]:
cosine_similarity

np.float64(0.7561198853864955)

以上是从向量的角度看待a和b。

### 从欧氏空间角度看

从欧式空间的角度看，a和b都是空间内的点。欧氏空间内的距离就是两点之间的距离。

在坐标系中，求a，b的距离时需要把两个点`分别`投射到x轴和y轴。

a的坐标为 $(x_1, y_1)$ ，b的坐标为 $(x_2, y_2)$ 

<img src="./欧氏空间内求两点距离.png" width=350>

In [32]:
((a - b) ** 2).sum() ** 0.5

np.float64(10.954451150103322)

In [33]:
# 以后可以这么写
np.linalg.norm(a - b)

np.float64(10.954451150103322)

### 3.如何看待数据
- 两个视角
    - 线性代数：向量：
        - 余弦相似度
            - 余弦相似度越高，代表样本越相似
    - 欧式空间：点：
        - 欧式距离：
            - 欧式距离越小，代表样本越相似