In [1]:
import torch
from torch import nn

In [2]:
dropout = nn.Dropout(p=0.5)

In [3]:
x = torch.randn(5)

In [4]:
x

tensor([ 1.8560, -0.4352,  1.0457,  0.4158,  1.5081])

In [5]:
dropout.train()

Dropout(p=0.5, inplace=False)

In [6]:
dropout(x)

tensor([3.7120, -0.0000, 0.0000, 0.8315, 3.0161])

In [7]:
dropout.eval()

Dropout(p=0.5, inplace=False)

In [8]:
x

tensor([ 1.8560, -0.4352,  1.0457,  0.4158,  1.5081])

In [9]:
dropout(x)

tensor([ 1.8560, -0.4352,  1.0457,  0.4158,  1.5081])