### 1. 数据读取

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(filepath_or_buffer="./信用卡客户流失数据集.csv")

In [3]:
data.shape

(10134, 21)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10134 entries, 0 to 10133
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   CLIENTNUM                 10134 non-null  int64  
 1   Attrition_Flag            10134 non-null  object 
 2   Customer_Age              10134 non-null  int64  
 3   Gender                    10134 non-null  object 
 4   Dependent_count           10134 non-null  int64  
 5   Education_Level           10133 non-null  object 
 6   Marital_Status            10134 non-null  object 
 7   Income_Category           10134 non-null  object 
 8   Card_Category             10133 non-null  object 
 9   Months_on_book            10134 non-null  int64  
 10  Total_Relationship_Count  10134 non-null  int64  
 11  Months_Inactive_12_mon    10134 non-null  int64  
 12  Contacts_Count_12_mon     10134 non-null  int64  
 13  Credit_Limit              10134 non-null  float64
 14  Total_

In [5]:
data.head()

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0  768805383  Existing Customer            45      M                3   
1  818770008  Existing Customer            49      F                5   
2  713982108  Existing Customer            51      M                3   
3  769911858  Existing Customer            40      F                4   
4  709106358  Existing Customer            40      M                3   

  Education_Level Marital_Status Income_Category Card_Category  \
0     High School        Married     $60K - $80K          Blue   
1        Graduate         Single  Less than $40K          Blue   
2        Graduate        Married    $80K - $120K          Blue   
3     High School        Unknown  Less than $40K          Blue   
4      Uneducated        Married     $60K - $80K          Blue   

   Months_on_book  ...  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0              39  ...                       1                      3   
1              44  ...                       1                      2   
2              36  ...                       1                      0   
3              34  ...                       4                      1   
4              21  ...                       1                      0   

   Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0       12691.0                  777          11914.0                 1.335   
1        8256.0                  864           7392.0                 1.541   
2        3418.0                    0           3418.0                 2.594   
3        3313.0                 2517            796.0                 1.405   
4        4716.0                    0           4716.0                 2.175   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             1144              42                1.625                  0.061  
1             1291              33                3.714                  0.105  
2             1887              20                2.333                  0.000  
3             1171              20                2.333                  0.760  
4              816              28                2.500                  0.000  

[5 rows x 21 columns]

In [6]:
data.tail(n=3)

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
10131  714337233  Attrited Customer            43      F                2   
10132   78874666  Existing Customer            53      F                1   
10133   71737777  Existing Customer            56      M                3   

      Education_Level Marital_Status Income_Category Card_Category  \
10131        Graduate        Married  Less than $40K        Silver   
10132        Graduate        Married  Less than $40K           NaN   
10133             NaN         Single         $120K +          Blue   

       Months_on_book  ...  Months_Inactive_12_mon  Contacts_Count_12_mon  \
10131              25  ...                       2                      4   
10132              32  ...                       2                      3   
10133              44  ...                       1                      2   

       Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
10131       10388.0                 1961           8427.0   
10132        7832.0                 1784           6048.0   
10133       34516.0                 1307          33209.0   

       Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
10131                 0.703            10294              61   
10132                 0.711            14614             106   
10133                 0.558            13759             120   

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
10131                0.649                  0.189  
10132                0.656                  0.228  
10133                0.765                  0.038  

[3 rows x 21 columns]

In [7]:
data.sample(n=3)

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
7793  805524708  Attrited Customer            52      F                3   
4088  710905908  Existing Customer            43      M                4   
4204  741116058  Existing Customer            48      M                2   

     Education_Level Marital_Status Income_Category Card_Category  \
7793     High School       Divorced  Less than $40K          Blue   
4088     High School         Single     $60K - $80K          Blue   
4204        Graduate        Married     $40K - $60K          Blue   

      Months_on_book  ...  Months_Inactive_12_mon  Contacts_Count_12_mon  \
7793              47  ...                       3                      1   
4088              36  ...                       3                      3   
4204              41  ...                       2                      4   

      Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
7793        6629.0                 2517           4112.0   
4088        4983.0                 1355           3628.0   
4204        2582.0                 1399           1183.0   

      Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
7793                 0.932             2599              50   
4088                 0.660             1939              30   
4204                 0.559             2144              42   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
7793                0.562                  0.380  
4088                0.500                  0.272  
4204                0.909                  0.542  

[3 rows x 21 columns]

### 2. 数据清洗
- 重复
    - 什么叫重复？user_id?
- 缺失
- 异常

In [8]:
# 只是判断是否有重复
data.duplicated(subset=["CLIENTNUM"]).sum()

np.int64(5)

In [9]:
# 删除重复（注意：删除多余的，保留其中一条）
# inplace  覆盖原数据
data.drop_duplicates(subset=["CLIENTNUM"], inplace=True)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10129 entries, 0 to 10133
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   CLIENTNUM                 10129 non-null  int64  
 1   Attrition_Flag            10129 non-null  object 
 2   Customer_Age              10129 non-null  int64  
 3   Gender                    10129 non-null  object 
 4   Dependent_count           10129 non-null  int64  
 5   Education_Level           10128 non-null  object 
 6   Marital_Status            10129 non-null  object 
 7   Income_Category           10129 non-null  object 
 8   Card_Category             10128 non-null  object 
 9   Months_on_book            10129 non-null  int64  
 10  Total_Relationship_Count  10129 non-null  int64  
 11  Months_Inactive_12_mon    10129 non-null  int64  
 12  Contacts_Count_12_mon     10129 non-null  int64  
 13  Credit_Limit              10129 non-null  float64
 14  Total_Revol

In [11]:
# 判断是否缺失 等效于 data.isnull()
data.isna().sum()

CLIENTNUM                   0
Attrition_Flag              0
Customer_Age                0
Gender                      0
Dependent_count             0
Education_Level             1
Marital_Status              0
Income_Category             0
Card_Category               1
Months_on_book              0
Total_Relationship_Count    0
Months_Inactive_12_mon      0
Contacts_Count_12_mon       0
Credit_Limit                0
Total_Revolving_Bal         0
Avg_Open_To_Buy             0
Total_Amt_Chng_Q4_Q1        0
Total_Trans_Amt             0
Total_Trans_Ct              0
Total_Ct_Chng_Q4_Q1         0
Avg_Utilization_Ratio       0
dtype: int64

In [12]:
# 删除缺失数据
# how=“all” 的话就是这一行全缺失，那就删
data.dropna(how="any", inplace=True)

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10127 entries, 0 to 10126
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   CLIENTNUM                 10127 non-null  int64  
 1   Attrition_Flag            10127 non-null  object 
 2   Customer_Age              10127 non-null  int64  
 3   Gender                    10127 non-null  object 
 4   Dependent_count           10127 non-null  int64  
 5   Education_Level           10127 non-null  object 
 6   Marital_Status            10127 non-null  object 
 7   Income_Category           10127 non-null  object 
 8   Card_Category             10127 non-null  object 
 9   Months_on_book            10127 non-null  int64  
 10  Total_Relationship_Count  10127 non-null  int64  
 11  Months_Inactive_12_mon    10127 non-null  int64  
 12  Contacts_Count_12_mon     10127 non-null  int64  
 13  Credit_Limit              10127 non-null  float64
 14  Total_Revol

In [14]:
data.sample(n=3)

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
9787  710527533  Attrited Customer            45      M                5   
8618  778894233  Existing Customer            42      M                5   
7201  717870108  Existing Customer            46      F                4   

     Education_Level Marital_Status Income_Category Card_Category  \
9787         College         Single     $40K - $60K          Blue   
8618     High School        Unknown    $80K - $120K          Blue   
7201         Unknown        Unknown     $40K - $60K          Blue   

      Months_on_book  ...  Months_Inactive_12_mon  Contacts_Count_12_mon  \
9787              36  ...                       3                      3   
8618              23  ...                       2                      3   
7201              37  ...                       4                      2   

      Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
9787        4982.0                    0           4982.0   
8618        7253.0                    0           7253.0   
7201        1912.0                 1172            740.0   

      Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
9787                 0.886             8586              58   
8618                 0.644             7595              83   
7201                 0.827             4841              81   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
9787                1.000                  0.000  
8618                0.804                  0.000  
7201                0.884                  0.613  

[3 rows x 21 columns]

In [15]:
# 删除无用的列
data.drop(columns=["CLIENTNUM"], inplace=True)

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10127 entries, 0 to 10126
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Attrition_Flag            10127 non-null  object 
 1   Customer_Age              10127 non-null  int64  
 2   Gender                    10127 non-null  object 
 3   Dependent_count           10127 non-null  int64  
 4   Education_Level           10127 non-null  object 
 5   Marital_Status            10127 non-null  object 
 6   Income_Category           10127 non-null  object 
 7   Card_Category             10127 non-null  object 
 8   Months_on_book            10127 non-null  int64  
 9   Total_Relationship_Count  10127 non-null  int64  
 10  Months_Inactive_12_mon    10127 non-null  int64  
 11  Contacts_Count_12_mon     10127 non-null  int64  
 12  Credit_Limit              10127 non-null  float64
 13  Total_Revolving_Bal       10127 non-null  int64  
 14  Avg_Open_To

### 3, 数据预处理
- 编码问题
- 异常问题
- 量纲问题

In [17]:
data.shape

(10127, 20)

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10127 entries, 0 to 10126
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Attrition_Flag            10127 non-null  object 
 1   Customer_Age              10127 non-null  int64  
 2   Gender                    10127 non-null  object 
 3   Dependent_count           10127 non-null  int64  
 4   Education_Level           10127 non-null  object 
 5   Marital_Status            10127 non-null  object 
 6   Income_Category           10127 non-null  object 
 7   Card_Category             10127 non-null  object 
 8   Months_on_book            10127 non-null  int64  
 9   Total_Relationship_Count  10127 non-null  int64  
 10  Months_Inactive_12_mon    10127 non-null  int64  
 11  Contacts_Count_12_mon     10127 non-null  int64  
 12  Credit_Limit              10127 non-null  float64
 13  Total_Revolving_Bal       10127 non-null  int64  
 14  Avg_Open_To

In [19]:
attrition_dict = {attrition:index for index, attrition in enumerate(data['Attrition_Flag'].unique())}
print(attrition_dict)

{'Existing Customer': 0, 'Attrited Customer': 1}


In [20]:
data['Attrition_Flag'].unique()

array(['Existing Customer', 'Attrited Customer'], dtype=object)

In [21]:
"""
    1, Attrition_Flag
"""
# 判断有多少个离散的状态
data["Attrition_Flag"].unique()
# 构建 状态字典
attrition_dict = {attrition:idx for idx, attrition in enumerate(data["Attrition_Flag"].unique())}
# 更新对应的列
data["Attrition_Flag"] = data["Attrition_Flag"].apply(func=lambda ele: attrition_dict[ele])
idx2label = {idx: attrition for attrition, idx in attrition_dict.items()}

In [22]:
"""
    2, Customer_Age

    | 按位或
    & 按位与
    ! 按位取反
"""
# 异常判断
((data["Customer_Age"] < 0) | (data["Customer_Age"] > 150)).sum()

np.int64(0)

In [23]:
"""
    3, Gender
"""
# 判断有多少个离散的状态
data["Gender"].unique()
# 构建 状态字典
gender_dict = {gender: idx for idx, gender in enumerate(data["Gender"].unique())}
# 更新对应的列
data["Gender"] = data["Gender"].apply(func=lambda ele: gender_dict[ele])

In [24]:
"""
    4, Dependent_count
"""
data["Dependent_count"].unique()

array([3, 5, 4, 2, 0, 1])

In [25]:
"""
    5, Education_Level
"""
data["Education_Level"].unique()
# 构建 状态字典
education_dict = {education: idx for idx, education in enumerate(data["Education_Level"].unique())}
# 更新对应的列
data["Education_Level"] = data["Education_Level"].apply(func=lambda ele: education_dict[ele])

In [26]:
"""
    6, Marital_Status
"""
data["Marital_Status"].unique()
# 构建 状态字典
marital_dict = {marital: idx for idx, marital in enumerate(data["Marital_Status"].unique())}
# 更新对应的列
data["Marital_Status"] = data["Marital_Status"].apply(func=lambda ele: marital_dict[ele])

In [27]:
"""
    7, Income_Category
"""
data["Income_Category"].unique()
# 构建 状态字典
income_dict = {income: idx for idx, income in enumerate(data["Income_Category"].unique())}
# 更新对应的列
data["Income_Category"] = data["Income_Category"].apply(func=lambda ele: income_dict[ele])

In [28]:
"""
    8，Card_Category
"""
data["Card_Category"].unique()
# 构建 状态字典
card_dict = {card: idx for idx, card in enumerate(data["Card_Category"].unique())}
# 更新对应的列
data["Card_Category"] = data["Card_Category"].apply(func=lambda ele: card_dict[ele])

In [29]:
"""
    9, Months_on_book
"""
data["Months_on_book"].unique()

array([39, 44, 36, 34, 21, 46, 27, 31, 54, 30, 48, 37, 56, 42, 49, 33, 28,
       38, 41, 43, 45, 52, 40, 50, 35, 47, 32, 20, 29, 25, 53, 24, 55, 23,
       22, 26, 13, 51, 19, 15, 17, 18, 16, 14])

In [30]:
"""
    10, Total_Relationship_Count
"""
data["Total_Relationship_Count"].unique()

array([5, 6, 4, 3, 2, 1])

In [31]:
"""
    11, Months_Inactive_12_mon
"""
data["Months_Inactive_12_mon"].unique()

array([1, 4, 2, 3, 6, 0, 5])

In [32]:
"""
    12, Contacts_Count_12_mon
"""
data["Contacts_Count_12_mon"].unique()

array([3, 2, 0, 1, 4, 5, 6])

In [33]:
"""
    13, Credit_Limit
"""
data["Credit_Limit"].min(), data["Credit_Limit"].max(), data["Credit_Limit"].mean()

(np.float64(1438.3), np.float64(34516.0), np.float64(8631.953698034955))

In [34]:
"""
    14, Total_Revolving_Bal
"""
data["Total_Revolving_Bal"].min(), data["Total_Revolving_Bal"].max(), data["Total_Revolving_Bal"].mean()

(np.int64(0), np.int64(2517), np.float64(1162.8140614199665))

In [35]:
"""
    15, Avg_Open_To_Buy
"""
data["Avg_Open_To_Buy"].min(), data["Avg_Open_To_Buy"].max(), data["Avg_Open_To_Buy"].mean()

(np.float64(3.0), np.float64(34516.0), np.float64(7469.139636614989))

In [36]:
"""
    16, Total_Amt_Chng_Q4_Q1
"""
data["Total_Amt_Chng_Q4_Q1"].min(), data["Total_Amt_Chng_Q4_Q1"].max(), data["Total_Amt_Chng_Q4_Q1"].mean()

(np.float64(0.0), np.float64(3.397), np.float64(0.7599406536980349))

In [37]:
"""
    17, Total_Trans_Amt
"""
data["Total_Trans_Amt"].min(), data["Total_Trans_Amt"].max(), data["Total_Trans_Amt"].mean()

(np.int64(510), np.int64(18484), np.float64(4404.086303939963))

In [38]:
"""
    18, Total_Trans_Ct
"""
data["Total_Trans_Ct"].min(), data["Total_Trans_Ct"].max(), data["Total_Trans_Ct"].mean()

(np.int64(10), np.int64(139), np.float64(64.85869457884863))

In [39]:
"""
    19, Total_Ct_Chng_Q4_Q1
"""
data["Total_Ct_Chng_Q4_Q1"].min(), data["Total_Ct_Chng_Q4_Q1"].max(), data["Total_Ct_Chng_Q4_Q1"].mean()

(np.float64(0.0), np.float64(3.714), np.float64(0.7122223758269972))

In [40]:
"""
    20，Avg_Utilization_Ratio
"""
data["Avg_Utilization_Ratio"].min(), data["Avg_Utilization_Ratio"].max(), data["Avg_Utilization_Ratio"].mean()

(np.float64(0.0), np.float64(0.999), np.float64(0.2748935518909845))

In [41]:
data.sample(n=3)

Attrition_Flag  Customer_Age  Gender  Dependent_count  Education_Level  \
8903               1            52       1                2                1   
8897               0            45       0                4                1   
1057               0            40       0                2                1   

      Marital_Status  Income_Category  Card_Category  Months_on_book  \
8903               1                5              0              41   
8897               1                4              3              34   
1057               0                2              0              31   

      Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
8903                         2                       3                      3   
8897                         2                       2                      1   
1057                         5                       1                      2   

      Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
8903        3608.0                 2517           1091.0   
8897       34516.0                 1488          33028.0   
1057       18693.0                 2052          16641.0   

      Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
8903                 1.057             4907              53   
8897                 0.732             7281              95   
1057                 0.500             1516              44   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
8903                0.559                  0.698  
8897                0.532                  0.043  
1057                0.630                  0.110

### 4，数据拆分

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10127 entries, 0 to 10126
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Attrition_Flag            10127 non-null  int64  
 1   Customer_Age              10127 non-null  int64  
 2   Gender                    10127 non-null  int64  
 3   Dependent_count           10127 non-null  int64  
 4   Education_Level           10127 non-null  int64  
 5   Marital_Status            10127 non-null  int64  
 6   Income_Category           10127 non-null  int64  
 7   Card_Category             10127 non-null  int64  
 8   Months_on_book            10127 non-null  int64  
 9   Total_Relationship_Count  10127 non-null  int64  
 10  Months_Inactive_12_mon    10127 non-null  int64  
 11  Contacts_Count_12_mon     10127 non-null  int64  
 12  Credit_Limit              10127 non-null  float64
 13  Total_Revolving_Bal       10127 non-null  int64  
 14  Avg_Open_To

In [43]:
y = data["Attrition_Flag"].to_numpy()

In [44]:
X = data.drop(columns=["Attrition_Flag"]).to_numpy()

In [45]:
X.shape, y.shape

((10127, 19), (10127,))

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [48]:
X_train.shape

(8101, 19)

In [49]:
X_test.shape

(2026, 19)

In [50]:
y_train.shape

(8101,)

In [51]:
y_test.shape

(2026,)

### 5. 数据标准化处理

标准化的公式：$ x = \frac{x - \mu}{\sigma}$

In [52]:
# 从训练集中抽取预处理参数 mu 和 sigma
mu = X_train.mean(axis=0)
sigma = X_train.std(axis=0)

In [53]:
mu

array([4.63714356e+01, 5.25984446e-01, 2.35032712e+00, 1.98197753e+00,
       7.57931120e-01, 2.02061474e+00, 1.26651031e-01, 3.59549438e+01,
       3.81150475e+00, 2.34304407e+00, 2.45562276e+00, 8.69590811e+03,
       1.16181360e+03, 7.53409451e+03, 7.59565362e-01, 4.38340995e+03,
       6.47243550e+01, 7.12633255e-01, 2.71742871e-01])

In [54]:
sigma

array([7.99046888e+00, 4.99324352e-01, 1.29434174e+00, 1.68121584e+00,
       8.82023834e-01, 1.53964830e+00, 4.82767610e-01, 7.96817019e+00,
       1.55566459e+00, 1.01693356e+00, 1.11289068e+00, 9.10740964e+03,
       8.19411770e+02, 9.10600361e+03, 2.19319993e-01, 3.39352315e+03,
       2.34557564e+01, 2.40238688e-01, 2.74914812e-01])

In [55]:
# 标准化前的X_train
X_train

array([[5.50e+01, 0.00e+00, 2.00e+00, ..., 3.40e+01, 1.00e+00, 1.41e-01],
       [3.20e+01, 0.00e+00, 0.00e+00, ..., 6.80e+01, 4.78e-01, 0.00e+00],
       [3.50e+01, 1.00e+00, 4.00e+00, ..., 8.00e+01, 7.02e-01, 1.74e-01],
       ...,
       [6.00e+01, 0.00e+00, 1.00e+00, ..., 6.70e+01, 9.14e-01, 1.67e-01],
       [5.10e+01, 0.00e+00, 3.00e+00, ..., 1.19e+02, 7.76e-01, 4.30e-02],
       [5.30e+01, 1.00e+00, 1.00e+00, ..., 3.70e+01, 6.82e-01, 8.13e-01]],
      shape=(8101, 19))

In [56]:
# 标准化前的X_test
X_test

array([[ 44.   ,   0.   ,   5.   , ...,  59.   ,   0.903,   0.1  ],
       [ 44.   ,   1.   ,   3.   , ...,  60.   ,   0.538,   0.   ],
       [ 37.   ,   1.   ,   3.   , ...,  67.   ,   0.489,   0.76 ],
       ...,
       [ 52.   ,   1.   ,   2.   , ...,  39.   ,   0.696,   0.881],
       [ 42.   ,   1.   ,   3.   , ...,  72.   ,   0.8  ,   0.811],
       [ 39.   ,   0.   ,   1.   , ..., 100.   ,   0.695,   0.217]],
      shape=(2026, 19))

In [57]:
# 执行标准化操作（执行预处理）
# 样本集进行标准化的主要原因是为了消除不同特征之间的量纲影响，使得所有特征能够在同一量级上进行比较和分析。
X_train = (X_train - mu) / sigma
X_test = (X_test - mu) / sigma

In [58]:
# 标准化后的X_train
X_train

array([[ 1.07985708, -1.05339234, -0.27066045, ..., -1.30988549,
         1.19617181, -0.47557594],
       [-1.79857225, -1.05339234, -1.81584743, ...,  0.13965207,
        -0.97666724, -0.9884621 ],
       [-1.42312495,  0.94931391,  1.27452653, ...,  0.65125357,
        -0.04426121, -0.35553876],
       ...,
       [ 1.70560258, -1.05339234, -1.04325394, ...,  0.09701861,
         0.83819449, -0.38100119],
       [ 0.57926067, -1.05339234,  0.50193304, ...,  2.31395842,
         0.26376578, -0.83205001],
       [ 0.82955888,  0.94931391, -1.04325394, ..., -1.18198512,
        -0.12751175,  1.96881763]], shape=(8101, 19))

In [59]:
# 标准化后的X_test
X_test

array([[-0.29678304, -1.05339234,  2.04712002, ..., -0.24404905,
         0.7924067 , -0.62471305],
       [-0.29678304,  0.94931391,  0.50193304, ..., -0.20141559,
        -0.72691562, -0.9884621 ],
       [-1.17282675,  0.94931391,  0.50193304, ...,  0.09701861,
        -0.93087944,  1.77603064],
       ...,
       [ 0.70440977,  0.94931391, -0.27066045, ..., -1.0967182 ,
        -0.06923637,  2.21616698],
       [-0.54708124,  0.94931391,  0.50193304, ...,  0.3101859 ,
         0.36366643,  1.96154265],
       [-0.92252854, -1.05339234, -1.04325394, ...,  1.50392272,
        -0.0733989 , -0.19912667]], shape=(2026, 19))

### 6, 数据保存
- 特征编码时的状态字典
- 特征的各种异常判断
- 标准化处理的参数

In [60]:
import joblib

In [61]:
state_dict = [idx2label, gender_dict, education_dict, marital_dict, income_dict, card_dict, mu, sigma]
data = [X_train, y_train, X_test, y_test]

In [62]:
state_dict

[{0: 'Existing Customer', 1: 'Attrited Customer'},
 {'M': 0, 'F': 1},
 {'High School': 0,
  'Graduate': 1,
  'Uneducated': 2,
  'Unknown': 3,
  'College': 4,
  'Post-Graduate': 5,
  'Doctorate': 6},
 {'Married': 0, 'Single': 1, 'Unknown': 2, 'Divorced': 3},
 {'$60K - $80K': 0,
  'Less than $40K': 1,
  '$80K - $120K': 2,
  '$40K - $60K': 3,
  '$120K +': 4,
  'Unknown': 5},
 {'Blue': 0, 'Gold': 1, 'Silver': 2, 'Platinum': 3},
 array([4.63714356e+01, 5.25984446e-01, 2.35032712e+00, 1.98197753e+00,
        7.57931120e-01, 2.02061474e+00, 1.26651031e-01, 3.59549438e+01,
        3.81150475e+00, 2.34304407e+00, 2.45562276e+00, 8.69590811e+03,
        1.16181360e+03, 7.53409451e+03, 7.59565362e-01, 4.38340995e+03,
        6.47243550e+01, 7.12633255e-01, 2.71742871e-01]),
 array([7.99046888e+00, 4.99324352e-01, 1.29434174e+00, 1.68121584e+00,
        8.82023834e-01, 1.53964830e+00, 4.82767610e-01, 7.96817019e+00,
        1.55566459e+00, 1.01693356e+00, 1.11289068e+00, 9.10740964e+03,
        8.

In [63]:
data

[array([[ 1.07985708, -1.05339234, -0.27066045, ..., -1.30988549,
          1.19617181, -0.47557594],
        [-1.79857225, -1.05339234, -1.81584743, ...,  0.13965207,
         -0.97666724, -0.9884621 ],
        [-1.42312495,  0.94931391,  1.27452653, ...,  0.65125357,
         -0.04426121, -0.35553876],
        ...,
        [ 1.70560258, -1.05339234, -1.04325394, ...,  0.09701861,
          0.83819449, -0.38100119],
        [ 0.57926067, -1.05339234,  0.50193304, ...,  2.31395842,
          0.26376578, -0.83205001],
        [ 0.82955888,  0.94931391, -1.04325394, ..., -1.18198512,
         -0.12751175,  1.96881763]], shape=(8101, 19)),
 array([0, 0, 0, ..., 0, 0, 0], shape=(8101,)),
 array([[-0.29678304, -1.05339234,  2.04712002, ..., -0.24404905,
          0.7924067 , -0.62471305],
        [-0.29678304,  0.94931391,  0.50193304, ..., -0.20141559,
         -0.72691562, -0.9884621 ],
        [-1.17282675,  0.94931391,  0.50193304, ...,  0.09701861,
         -0.93087944,  1.77603064],
 

In [64]:
joblib.dump(value=[state_dict, data], filename="all_data.lxh")

['all_data.lxh']