### 1, 数据加载

In [1]:
import joblib

In [2]:
[state_dict, data] = joblib.load(filename="all_data.lxh")

In [3]:
state_dict

[{0: 'Existing Customer', 1: 'Attrited Customer'},
 {'M': 0, 'F': 1},
 {'High School': 0,
  'Graduate': 1,
  'Uneducated': 2,
  'Unknown': 3,
  'College': 4,
  'Post-Graduate': 5,
  'Doctorate': 6},
 {'Married': 0, 'Single': 1, 'Unknown': 2, 'Divorced': 3},
 {'$60K - $80K': 0,
  'Less than $40K': 1,
  '$80K - $120K': 2,
  '$40K - $60K': 3,
  '$120K +': 4,
  'Unknown': 5},
 {'Blue': 0, 'Gold': 1, 'Silver': 2, 'Platinum': 3},
 array([4.63714356e+01, 5.25984446e-01, 2.35032712e+00, 1.98197753e+00,
        7.57931120e-01, 2.02061474e+00, 1.26651031e-01, 3.59549438e+01,
        3.81150475e+00, 2.34304407e+00, 2.45562276e+00, 8.69590811e+03,
        1.16181360e+03, 7.53409451e+03, 7.59565362e-01, 4.38340995e+03,
        6.47243550e+01, 7.12633255e-01, 2.71742871e-01]),
 array([7.99046888e+00, 4.99324352e-01, 1.29434174e+00, 1.68121584e+00,
        8.82023834e-01, 1.53964830e+00, 4.82767610e-01, 7.96817019e+00,
        1.55566459e+00, 1.01693356e+00, 1.11289068e+00, 9.10740964e+03,
        8.

In [4]:
data

[array([[ 1.07985708, -1.05339234, -0.27066045, ..., -1.30988549,
          1.19617181, -0.47557594],
        [-1.79857225, -1.05339234, -1.81584743, ...,  0.13965207,
         -0.97666724, -0.9884621 ],
        [-1.42312495,  0.94931391,  1.27452653, ...,  0.65125357,
         -0.04426121, -0.35553876],
        ...,
        [ 1.70560258, -1.05339234, -1.04325394, ...,  0.09701861,
          0.83819449, -0.38100119],
        [ 0.57926067, -1.05339234,  0.50193304, ...,  2.31395842,
          0.26376578, -0.83205001],
        [ 0.82955888,  0.94931391, -1.04325394, ..., -1.18198512,
         -0.12751175,  1.96881763]], shape=(8101, 19)),
 array([0, 0, 0, ..., 0, 0, 0], shape=(8101,)),
 array([[-0.29678304, -1.05339234,  2.04712002, ..., -0.24404905,
          0.7924067 , -0.62471305],
        [-0.29678304,  0.94931391,  0.50193304, ..., -0.20141559,
         -0.72691562, -0.9884621 ],
        [-1.17282675,  0.94931391,  0.50193304, ...,  0.09701861,
         -0.93087944,  1.77603064],
 

In [5]:
idx2label, gender_dict, education_dict, marital_dict, income_dict, card_dict, mu, sigma = state_dict
X_train, y_train, X_test, y_test = data

In [6]:
gender_dict

{'M': 0, 'F': 1}

In [7]:
# import joblib
# joblib.dump(value=[idx2label, gender_dict, education_dict, marital_dict, income_dict, card_dict, mu, sigma], filename="state.lxh")

### 2. 尝试所有算法
- 二分类问题
- 算法：
  - KNN
  - 朴素贝叶斯
  - 决策树

### 2.1 KNN算法

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
knn = KNeighborsClassifier(n_neighbors=5)

In [10]:
knn.fit(X=X_train, y=y_train)

KNeighborsClassifier()

In [11]:
y_pred = knn.predict(X=X_test)

In [12]:
acc = (y_pred == y_test).mean()

In [13]:
acc

np.float64(0.9042448173741362)

In [43]:
# 初始化相关参数
best_n_neighbor = 0
best_acc = 0
best_model = None
# 简单遍历，寻找比较好的 N
for n_neighbor in range(3, 101, 1):
    knn = KNeighborsClassifier(n_neighbors=n_neighbor)
    knn.fit(X=X_train, y=y_train)
    y_pred = knn.predict(X=X_test)
    acc = (y_pred == y_test).mean()
    if acc > best_acc:
        best_acc = acc
        best_n_neighbor = n_neighbor
        best_model = knn
        print(f'找到一个更好的模型：n_neighbor = {best_n_neighbor}, acc = {best_acc}')

找到一个更好的模型：n_neighbor = 3, acc = 0.9002961500493584
找到一个更好的模型：n_neighbor = 5, acc = 0.9042448173741362
找到一个更好的模型：n_neighbor = 7, acc = 0.9067127344521224
找到一个更好的模型：n_neighbor = 9, acc = 0.9081934846989141


In [15]:
# 最好邻居数
best_n_neighbor

9

In [16]:
# 最好正确率
best_acc

np.float64(0.9081934846989141)

In [17]:
# 保存模型
joblib.dump(value=[best_n_neighbor, best_acc, best_model], filename="best_knn.lxh")

['best_knn.lxh']

In [18]:
# 加载模型
joblib.load(filename="best_knn.lxh")

[9, np.float64(0.9081934846989141), KNeighborsClassifier(n_neighbors=9)]

### 2.2 朴素贝叶斯
- 高斯朴素贝叶斯
- 高斯：假定所有的特征都是连续型的

In [19]:
from sklearn.naive_bayes import GaussianNB

In [20]:
gnb = GaussianNB()

In [21]:
gnb.fit(X=X_train, y=y_train)

GaussianNB()

In [22]:
y_pred = gnb.predict(X=X_test)

In [23]:
acc = (y_pred == y_test).mean()

In [24]:
acc

np.float64(0.8820335636722606)

### 2.3  决策树

In [25]:
from sklearn.tree import DecisionTreeClassifier

In [26]:
dtc = DecisionTreeClassifier()

In [27]:
dtc.fit(X=X_train, y=y_train)

DecisionTreeClassifier()

In [28]:
y_pred = dtc.predict(X=X_test)

In [29]:
acc = (y_pred == y_test).mean()

In [30]:
acc

np.float64(0.9333662388943732)

In [31]:
joblib.dump(value=dtc, filename="dtc.lxh")

['dtc.lxh']

### 3. 推理过程

In [32]:
# 推理的时候，是从数据中抽取随机一条进行比如："787584108,Existing Customer,55,M,3,Unknown,Married,$80K - $120K,Blue,47,4,2,3,3436,2016,1420,0.901,1097,33,0.833,0.587"

In [33]:
x = "787584108,55,M,3,Unknown,Married,$80K - $120K,Blue,47,4,2,3,3436,2016,1420,0.901,1097,33,0.833,0.587"

In [34]:
x1 = "719808558,55,F,2,Graduate,Married,Less than $40K,Blue,43,2,4,3,1438.3,0,1438.3,0.707,886,27,0.421,0"

In [35]:
def predict(x):
    """
        推理函数
    """
    import numpy as np
    print(f"原始输入：{x}")
    x = x.split(",")[1:]
    print(f"切分之后：{x}")
    temp = []
    # 1, age
    temp.append(float(x[0]))
    # 2, gender
    temp.append(gender_dict[x[1]])
    # 3, 
    temp.append(float(x[2]))
    # 4, 
    temp.append(education_dict[x[3]])

    # 5, 
    temp.append(marital_dict[x[4]])
    # 6，
    temp.append(income_dict[x[5]])

    # 7, 
    temp.append(card_dict[x[6]])

    # 8 - 19
    temp.extend([float(ele) for ele in x[7: ]])
    
    print(f"编码之后：{temp}")

    # 标准化
    x = np.array(temp)
    x = (x - mu) / sigma
    print(f"标准化后：{x}")

    # 进行模型推理
    y_pred = dtc.predict(X=[x])
    print(f"推理结果：{y_pred}")  

    # 推理结果是0，看不懂，所以进行结果解析
    final_result = idx2label[y_pred[0]]
    print(f"最终结果：{final_result}")
    
    return final_result 

In [36]:
predict(x=x)

原始输入：787584108,55,M,3,Unknown,Married,$80K - $120K,Blue,47,4,2,3,3436,2016,1420,0.901,1097,33,0.833,0.587
切分之后：['55', 'M', '3', 'Unknown', 'Married', '$80K - $120K', 'Blue', '47', '4', '2', '3', '3436', '2016', '1420', '0.901', '1097', '33', '0.833', '0.587']
编码之后：[55.0, 0, 3.0, 3, 0, 2, 0, 47.0, 4.0, 2.0, 3.0, 3436.0, 2016.0, 1420.0, 0.901, 1097.0, 33.0, 0.833, 0.587]
标准化后：[ 1.07985708 -1.05339234  0.50193304  0.60552753 -0.85930911 -0.01338925
 -0.26234368  1.38614712  0.12116702 -0.33733184  0.48915608 -0.57754162
  1.04243852 -0.67143555  0.644878   -0.96843599 -1.35251895  0.50102981
  1.14674479]
推理结果：[0]
最终结果：Existing Customer


'Existing Customer'

In [37]:
predict(x=x1)

原始输入：719808558,55,F,2,Graduate,Married,Less than $40K,Blue,43,2,4,3,1438.3,0,1438.3,0.707,886,27,0.421,0
切分之后：['55', 'F', '2', 'Graduate', 'Married', 'Less than $40K', 'Blue', '43', '2', '4', '3', '1438.3', '0', '1438.3', '0.707', '886', '27', '0.421', '0']
编码之后：[55.0, 1, 2.0, 1, 0, 1, 0, 43.0, 2.0, 4.0, 3.0, 1438.3, 0.0, 1438.3, 0.707, 886.0, 27.0, 0.421, 0.0]
标准化后：[ 1.07985708  0.94931391 -0.27066045 -0.58408772 -0.85930911 -0.66288823
 -0.26234368  0.88414981 -1.16445715  1.62936497  0.48915608 -0.79689049
 -1.41786297 -0.66942588 -0.23967428 -1.03061326 -1.6083197  -1.21393127
 -0.9884621 ]
推理结果：[1]
最终结果：Attrited Customer


'Attrited Customer'

### 4, 服务端 C/S 架构部署
- FastAPI web
- 代码实现：参考service文件夹 、client文件夹

### 5. 扩展
- 评价指标
  - 准确率 accuracy
