假设函数：$ y = k_1x_1 + k_2x_2 + ... + k_nx_n + b $

怕你看懂，改成： $ y = w_1x_1 + w_2x_2 + ... + w_nx_n + b $ ， $w$就是权重， $b$叫偏置

### 1. 读取数据

In [12]:
import pandas as pd

In [13]:
data = pd.read_csv(filepath_or_buffer="./boston_house_prices.csv", skiprows=1)

In [14]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [16]:
X = data.drop(columns=["MEDV"]).to_numpy()
y = data["MEDV"].to_numpy()

### 2. 切分&标准化

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=0)

In [19]:
X.shape

(506, 13)

In [20]:
y.shape

(506,)

In [21]:
mu = X_train.mean(axis=0)
sigma = X_train.std(axis=0)

In [22]:
# 标准化
X_train1 = (X_train - mu) / sigma
X_test1 = (X_test - mu) / sigma

In [23]:
# 查看结果，量纲已统一
print(f'X_train1:{X_train1}\n')
print(f'X_test1:{X_test1}')

X_train1:[[-0.37257438 -0.49960763 -0.70492455 ... -0.48463784  0.3716906
  -0.41100022]
 [-0.39709866 -0.49960763 -0.04487755 ...  0.33649132  0.20501196
  -0.38768057]
 [-0.402693    0.77116771 -0.88675963 ... -0.84958414  0.36660893
  -0.18191902]
 ...
 [-0.39805586 -0.49960763 -0.15941933 ... -0.30216469  0.40342278
  -0.33006734]
 [-0.38842357 -0.49960763 -0.60326872 ... -0.25654641  0.38343489
   0.8359148 ]
 [-0.39951258 -0.49960763 -1.01275558 ... -0.84958414  0.43041207
   0.27212814]]

X_test1:[[-0.40835869 -0.49960763 -1.12872913 ... -0.71272928  0.18547577
  -0.73610347]
 [ 0.71925111 -0.49960763  0.9988844  ...  0.79267419  0.0831649
  -0.4356916 ]
 [-0.40257488 -0.49960763  0.39610829 ... -0.94082071  0.39472748
  -0.30263246]
 ...
 [-0.3982601   0.55937182 -0.85812418 ...  0.56458276  0.41019833
   0.06087961]
 [-0.39934279 -0.49960763 -0.07637654 ...  0.0627816   0.30517724
  -0.45626776]
 [-0.40088071 -0.49960763 -0.36702631 ...  1.1120022   0.41166637
  -0.05983383]]


### 3. 套用模型

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lr = LinearRegression()

In [26]:
lr.fit(X=X_train1, y=y_train)

LinearRegression()

In [27]:
# 上面说到了有 w，b
# 训练完的模型，这两个参数是固定下来了,有13个特征，所以有13个w，查看下权重：
lr.coef_

array([-0.97082019,  1.05714873,  0.03831099,  0.59450642, -1.8551476 ,
        2.57321942, -0.08761547, -2.88094259,  2.11224542, -1.87533131,
       -2.29276735,  0.71817947, -3.59245482])

In [28]:
# 查看下偏置b
lr.intercept_

np.float64(22.611881188118836)

In [29]:
y_pred_lr = lr.predict(X=X_test1)

In [30]:
y_pred_lr

array([24.88963777, 23.72141085, 29.36499868, 12.12238621, 21.44382254,
       19.2834443 , 20.49647539, 21.36099298, 18.8967118 , 19.9280658 ,
        5.12703513, 16.3867396 , 17.07776485,  5.59375659, 39.99636726,
       32.49654668, 22.45798809, 36.85192327, 30.86401089, 23.15140009,
       24.77495789, 24.67187756, 20.59543752, 30.35369168, 22.41940736,
       10.23266565, 17.64816865, 18.27419652, 35.53362541, 20.96084724,
       18.30413012, 17.79262072, 19.96561663, 24.06127231, 29.10204874,
       19.27774123, 11.15536648, 24.57560579, 17.5862644 , 15.49454112,
       26.20577527, 20.86304693, 22.31460516, 15.60710156, 23.00363104,
       25.17247952, 20.11459464, 22.90256276, 10.0380507 , 24.28515123,
       20.94127711, 17.35258791, 24.52235405, 29.95143046, 13.42695877,
       21.72673066, 20.7897053 , 15.49668805, 13.98982601, 22.18377874,
       17.73047814, 21.58869165, 32.90522136, 31.11235671, 17.73252635,
       32.76358681, 18.7124637 , 19.78693475, 19.02958927, 22.89

In [31]:
y_test

array([22.6, 50. , 23. ,  8.3, 21.2, 19.9, 20.6, 18.7, 16.1, 18.6,  8.8,
       17.2, 14.9, 10.5, 50. , 29. , 23. , 33.3, 29.4, 21. , 23.8, 19.1,
       20.4, 29.1, 19.3, 23.1, 19.6, 19.4, 38.7, 18.7, 14.6, 20. , 20.5,
       20.1, 23.6, 16.8,  5.6, 50. , 14.5, 13.3, 23.9, 20. , 19.8, 13.8,
       16.5, 21.6, 20.3, 17. , 11.8, 27.5, 15.6, 23.1, 24.3, 42.8, 15.6,
       21.7, 17.1, 17.2, 15. , 21.7, 18.6, 21. , 33.1, 31.5, 20.1, 29.8,
       15.2, 15. , 27.5, 22.6, 20. , 21.4, 23.5, 31.2, 23.7,  7.4, 48.3,
       24.4, 22.6, 18.3, 23.3, 17.1, 27.9, 44.8, 50. , 23. , 21.4, 10.2,
       23.3, 23.2, 18.9, 13.4, 21.9, 24.8, 11.9, 24.3, 13.8, 24.7, 14.1,
       18.7, 28.1, 19.8])

In [32]:
# 由于是连续量，所以不存在准确率一说。所以衡量模型时直接做差
# 预测大了就是正数，预测小了就是负数，绝对值越小说明预测的越准
y_pred_lr - y_test

array([  2.28963777, -26.27858915,   6.36499868,   3.82238621,
         0.24382254,  -0.6165557 ,  -0.10352461,   2.66099298,
         2.7967118 ,   1.3280658 ,  -3.67296487,  -0.8132604 ,
         2.17776485,  -4.90624341, -10.00363274,   3.49654668,
        -0.54201191,   3.55192327,   1.46401089,   2.15140009,
         0.97495789,   5.57187756,   0.19543752,   1.25369168,
         3.11940736, -12.86733435,  -1.95183135,  -1.12580348,
        -3.16637459,   2.26084724,   3.70413012,  -2.20737928,
        -0.53438337,   3.96127231,   5.50204874,   2.47774123,
         5.55536648, -25.42439421,   3.0862644 ,   2.19454112,
         2.30577527,   0.86304693,   2.51460516,   1.80710156,
         6.50363104,   3.57247952,  -0.18540536,   5.90256276,
        -1.7619493 ,  -3.21484877,   5.34127711,  -5.74741209,
         0.22235405, -12.84856954,  -2.17304123,   0.02673066,
         3.6897053 ,  -1.70331195,  -1.01017399,   0.48377874,
        -0.86952186,   0.58869165,  -0.19477864,  -0.38

In [33]:
# 这时有几个衡量指标：    平均绝对误差.即 MAE(Mean Absolute Error)
abs(y_pred_lr - y_test).mean()

np.float64(3.8429092204444943)

In [34]:
# 平均平方误差.即 MSE(Mean Squared Error)
# 它会把大的误差放的更大，小的误差缩的更小，以后更多的会用MSE
loss_lr = ((y_pred_lr - y_test) ** 2).mean()
print(f'KNN的平均平方误差：{loss_lr}')

KNN的平均平方误差：33.448979997676496


In [35]:
# 用KNN尝试下
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X=X_train1, y=y_train)
y_pred_knn = knn.predict(X=X_test1)
loss_knn = ((y_pred_knn - y_test) ** 2).mean()
print(f'KNN的平均平方误差：{loss_knn}')

KNN的平均平方误差：35.67441568627451


In [36]:
# 用决策树尝试下
from sklearn.tree import DecisionTreeRegressor

dtr = DecisionTreeRegressor()
dtr.fit(X=X_train1, y=y_train)
y_pred_dtr = dtr.predict(X=X_test1)
loss_dtr = ((y_pred_dtr - y_test) ** 2).mean()
print(f'DTR的平均平方误差：{loss_dtr}')

DTR的平均平方误差：33.816078431372546


### 逻辑回归
- 二分类算法
- 在线性回归的基础上，增加了一个 sigmoid 激活函数
    - 线性回归的值域是 $(+\infty, -\infty)$ ，但是sigmoid激活函数是S型曲线，套上它之后，原本的线性回归的值域被压缩在了 $(0, 1)$
    - 所谓二分类算法，就是大于0.5就是第一类，小于0.5就是第二类  可以这么搞
- 优化：梯度下降法 SGD: Stoc**h**astic Gradient Descent

In [37]:
import joblib

In [38]:
_, [X_train, y_train, X_test, y_test] = joblib.load(filename="all_data.lxh")

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
lr = LogisticRegression()

In [41]:
lr.fit(X=X_train, y=y_train)

LogisticRegression()

In [42]:
y_pred = lr.predict(X=X_test)

In [43]:
(y_pred == y_test).mean() # 计算准确率

np.float64(0.9027640671273445)

In [44]:
X_train.shape

(8101, 19)

In [45]:
# 19个权重
lr.coef_

array([[-0.03432062,  0.30570988,  0.16714428,  0.08224422,  0.2046806 ,
         0.01729407,  0.09290679, -0.09146421, -0.71263014,  0.5350626 ,
         0.53159589, -0.04987557, -0.81509068,  0.02346338, -0.10912122,
         1.54194393, -2.69241636, -0.6710327 ,  0.01970949]])

In [46]:
# 1 个 偏置
lr.intercept_

array([-2.96643208])