In [1]:
import torch
import numpy as np

# 1.张量的基础操作

In [2]:
# 创建0维张量
data = torch.tensor(3)
print(f'直接输出：{data}, \n数据类型：{type(data)}, \n形状：{data.shape}')

直接输出：3, 
数据类型：<class 'torch.Tensor'>, 
形状：torch.Size([])


In [3]:
# 创建1维张量
data = torch.tensor([1.0, 2.0, 3.0])
print(f'直接输出：{data}, \n数据类型：{type(data)}, \n形状：{data.shape}')

直接输出：tensor([1., 2., 3.]), 
数据类型：<class 'torch.Tensor'>, 
形状：torch.Size([3])


In [4]:
# 创建2维张量
data = torch.tensor([[1, 2],
                     [3, 4],
                     [5, 6]], dtype=torch.float16)
print(f'直接输出：{data}, \n数据类型：{type(data)}, \n形状：{data.shape}')

直接输出：tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float16), 
数据类型：<class 'torch.Tensor'>, 
形状：torch.Size([3, 2])


In [5]:
# 创建3维张量
data = torch.tensor([
    [[1, 2, 3, 4, 5],
     [2, 3, 4, 5, 6]],
    [[1, 2, 3, 4, 5],
     [2, 3, 4, 5, 6]]
], dtype=torch.float64)
print(f'直接输出：{data}, \n数据类型：{type(data)}, \n形状：{data.shape}')

直接输出：tensor([[[1., 2., 3., 4., 5.],
         [2., 3., 4., 5., 6.]],

        [[1., 2., 3., 4., 5.],
         [2., 3., 4., 5., 6.]]], dtype=torch.float64), 
数据类型：<class 'torch.Tensor'>, 
形状：torch.Size([2, 2, 5])


# 转换成numpy

In [6]:
data = torch.tensor([1, 2, 3, 4, 5])
print(f'直接输出：{data}, \n数据类型：{type(data)}, \n形状：{data.shape}')
data = data.numpy()
print(f'直接输出：{data}, \n数据类型：{type(data)}, \n形状：{data.shape}')
data = np.array(data)
print(f'直接输出：{data}, \n数据类型：{type(data)}, \n形状：{data.shape}')

直接输出：tensor([1, 2, 3, 4, 5]), 
数据类型：<class 'torch.Tensor'>, 
形状：torch.Size([5])
直接输出：[1 2 3 4 5], 
数据类型：<class 'numpy.ndarray'>, 
形状：(5,)
直接输出：[1 2 3 4 5], 
数据类型：<class 'numpy.ndarray'>, 
形状：(5,)


# 3.常用函数

In [7]:
a = torch.tensor([[1, 2],
                 [3, 4]])
b = torch.tensor([[1, 1],
                 [1, 1]])

In [8]:
# 加法
torch.add(a, b)

tensor([[2, 3],
        [4, 5]])

In [9]:
# 元素相乘
torch.multiply(a, b)

tensor([[1, 2],
        [3, 4]])

In [10]:
# 矩阵乘法
# a.dtype
torch.matmul(a, b)

tensor([[3, 3],
        [7, 7]])

In [11]:
# 最大值
torch.max(a)

tensor(4)

In [12]:
# 全局最大值索引
torch.argmax(a)

tensor(3)

In [13]:
# 按维度最大值索引
torch.max(a, dim=1).indices

tensor([1, 1])

In [15]:
# 平均值
torch.mean(a.float())

tensor(2.5000)